language: rust
matrix:
  include:
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-gnu WIN=x86_64-pc-windows-gnu
      sudo: required
      addons:
        apt:
          packages:
            - gcc-mingw-w64

if: tag IS present
install: cargo install --force --path .
script: true
cache: cargo
before_deploy:
  - cargo build --release --target=$TARGET && mv target/release/badlogvis target/release/badlogvis-$TARGET
  - >-
      unset -e; test -n "$WIN"
      && rustup target add $WIN
      && printf "[target.$WIN]\nlinker = \"x86_64-w64-mingw32-gcc\"" >> ~/.cargo/config
      && cargo build --release --target=$WIN
      && mv target/$WIN/release/badlogvis.exe target/$WIN/release/badlogvis-$WIN.exe
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: target/**/release/badlogvis-{$TARGET,$WIN.exe}
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
