language: rust
matrix:
  include:
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-gnu WIN=x86_64-pc-windows-gnu

if: tag IS present
install: cargo install --force --path .
script: true
cache: cargo
before_deploy:
  - cargo build --release --target=$TARGET && mv target/release/badlogvis target/release/badlogvis-$TARGET
  - test -n "$WIN" && cargo build --release --target=$WIN && mv target/release/$WIN/badlogvis.exe target/release/$WIN/badlogvis-$WIN.exe
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: target/release/**/badlogvis-($TARGET|$WIN.exe)
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
